# Generated by Django 5.2.8 on 2025-11-30 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adoption_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='desexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='good_with_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='microchipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='special_needs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='suburb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='adoptions.animal')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
