# Generated by Django 5.2.8 on 2025-11-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
